### ISSUE TITLE
Class 'Laminas\Captcha\Image' not found

### ISSUE THREAD

**Issue by danielkoch** [columbusinteractive/typo3-easycaptcha#8]
I'm using the latest TER version from `easycaptcha` (`1.0.0`) with TYPO3 `v9.5.17` and getting the mentioned `not found` error.

Side note: I also tried the `1.1.0` and `master` from GitHub with the same result.
Side question: The latest version from GitHub is not on TER on purpose?

**Comment by into-the-v0id** [comment]
Make sure that the class exists (vendor/laminas/laminas-captcha/src/Image.php) and try running `composer dump-autoload`

**Comment by danielkoch** [comment]
It's not there. Looks like it's not shipped with the TER version (classic way – without `composer`).

**Comment by steff-B** [comment]
I get the same error and would be very interested in a solution too. I loaded the extension using the typo3 extension repository. "vendor/laminas/laminas-captcha/src/Image.php" doesn't exist.

**Comment by benjaminhirsch** [comment]
Hey @danielkoch,

the current version is only working in composer mode. Unfortunatley, non composer based TYPO3 installations aren't supported at the moment. 

We will look into this for a future release for non composer based installations.

**Comment by benjaminhirsch** [comment]
I've already spent some minutes to investige how much work has to be done to offer support for non composer based installations. Chances are good, that with our next release we are able to offer support. 😄

**Comment by benjaminhirsch** [comment]
I've added the necessary requirements to support non composer based installations. Next release will work in non composer based installations. 

Next step: setup a build pipeline for automatic release on TER. 😄

**Comment by benjaminhirsch** [comment]
@danielkoch - I've just released version 1.2.0 which adds support for non composer based installations. Please give it a try! 🙂

**Comment by danielkoch** [comment]
@benjaminhirsch: Thanks for the update. I get the following error:
```
(1/1) #1328710202 TYPO3\CMS\Form\Domain\Model\Exception\ValidatorPresetNotFoundException
The validator preset identified by "Easycaptcha" could not be found, or the implementationClassName was not specified.
```

**Comment by benjaminhirsch** [comment]
When exactly are you getting this error? Have you tried to remove the captcha from the form (save) and re add it?

**Comment by danielkoch** [comment]
On the form. I installed the extension in version `1.2.0`. Cleared all caches and added the new field from type captcha.

**Comment by benjaminhirsch** [comment]
On the form in the frontend? That's curious, because I've here locally a non composer based TYPO3 installation and was able to get the captcha running.... 🤔

**Comment by danielkoch** [comment]
Yes, on the frontend form. In the TYPO3 backend it works without any problems.

**Comment by benjaminhirsch** [comment]
Are you getting a stack trace? If so, could you please post it here.

**Comment by danielkoch** [comment]
Yes, I can provide more error information. BTW: You're also using TYPO3 `9.5.18`?

**Comment by benjaminhirsch** [comment]
Actually, the implementation was done in 10, but that shouldn't really be a problem in this case. But I will also give it a try in 9.5, just to be sure. It sounds more like a problem with the autoloading of the classes.

**Comment by benjaminhirsch** [comment]
Hey @danielkoch,

I've released version 1.2.1. There was indeed a bug which prevented the image to be generated because of the missing autoloader in non composer mode. Unfortunatley, I wasn't able to reproduce your error message, even in 9.5.18.  

I was able to get the extension running in Version 9 and 10 (non composer)

Please download the latest version (it might take a while until it appears on TER) and give it a try. Please make sure to disable and reanable the extension, clear the caches etc. Hopefully this will work for you now! 🙂

**Comment by danielkoch** [comment]
Thanks. But still get the same error 🤔 @steff-B what about you?

**Comment by benjaminhirsch** [comment]
I know it may sound stupid, but have you really proceeded in the following order:

1.) Remove the captcha element from your form
2.) Disable the captcha extension in the extension manager
3.) Clear all caches (i really mean all :D)
4.) Enable the captcha extension in the extension manager
5.) Add the captcha field again to your form
6.) Try it again

**Comment by danielkoch** [comment]
Not working for me :-(

**Comment by benjaminhirsch** [comment]
Good morning. Are you still getting this "The validator preset identified by "Easycaptcha" could not be found...." Message?

**Comment by danielkoch** [comment]
Yes.

**Comment by benjaminhirsch** [comment]
According to the message, this would mean that TYPO3 is unable to load the preset which actually is configured here:

https://github.com/columbusinteractive/typo3-easycaptcha/blob/ca95adf5d2a6760fdb0a1a6ccae21cbd658ce97c/Configuration/Yaml/BaseSetup.yaml#L17-L19

**Comment by benjaminhirsch** [comment]
Could you please follow these steps, just to make sure that autoloading is really working:
https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ApiOverview/Autoloading/Index.html

Especially this: php typo3/cli_dispatch.phpsh extbase extension:dumpclassloadinginformation

**Comment by steff-B** [comment]
It's working very well for me (Version 9.5.13)! Thank you very much for the quick help and the extension update! 
I just updated the extension using the extension manager, cleared the cache and embeded it to the template (I had to disable the extension after the first error) - that's it. Working nicely now! :)
